server:
  port: 8080
zuul:
  routes:
    users:
      url: http://user-service:8001
      path: /users/**
      stripPrefix: false
    catalogues:
      url: http://catalogue-service:8002
      path: /catalogues/**
      stripPrefix: false
    orders:
      url: http://order-service:8003
      path: /orders/**
      stripPrefix: false

---
spring:
  profiles: development
server:
  port: 8000
zuul:
  routes:
    users:
      url: http://user-service:8001
      path: /users/**
      stripPrefix: false
    catalogues:
      url: http://catalogue-service:8002
      path: /catalogues/**
      stripPrefix: false
    orders:
      url: http://order-service:8003
      path: /orders/**
      stripPrefix: false
debug: true